import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Riffs Anonymous</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Link href="/">
                <h2>&larr; Home</h2>
            </Link>

            <footer className={styles.footer}>
                <a target="_blank" rel="noopener noreferrer">
                    Created by Jake Chappell
                </a>
            </footer>
        </div>
    )
}
  
export default About