import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/footer'
import Navbar from '../components/navbar'

const Edit: NextPage = () => {
    return (
        <div className=''>
            <Head>
                <title>Riffs Anonymous</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='min-h-screen py-0 justify-center text-center align-middle bg-matte-darkgrey'>
                <Navbar/>

                {/* Edit modal */}
                <div className='modal-body p-6 bg-matte-black mx-24 my-10 shadow-md rounded-lg min-h-96 max-h-96 text-left border-4 border-matte-grey'>

                </div>
            </main>
            
            <Footer/>
        </div>
    )
}
  
export default Edit