import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/footer'
import Navbar from '../components/navbar'

const Edit: NextPage = () => {
    return (
        <div className=''>
            <Head>
                <title>Riffs Anonymous</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='min-h-screen py-0 justify-center text-center align-middle bg-matte-darkgrey'>
                <Navbar/>
                <h1 className='text-3xl text-white pt-5'>This is the edit page</h1>
            </main>
            
            <Footer/>
        </div>
    )
}
  
export default Edit