import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../components/footer'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div className='font-apple'>
      <Head>
        <title>Riffs Anonymous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen py-0 justify-center align-middle bg-matte-darkgrey'>
          <Navbar/>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
