import type { NextPage } from 'next'
import Head from 'next/head'
import SectionDivide from '../components/sectionDivide'
import Footer from '../components/footer'
import Navbar from '../components/navbar'

const Home: NextPage = () => {
  return (
    <div className='font-apple'>
      <Head>
        <title>Riffs Anonymous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen py-0 justify-center align-middle bg-matte-darkgrey'>
          <Navbar/>

          <div id="about-section" className='py-8 text-center'>
            <p className='text-matte-purple font-bold text-5xl'>Welcome to Riffs Anonymous!</p>
          </div>

          <SectionDivide/>
          <p className='text-white text-center text-lg'>Featured</p>


          <br/><br/>
          <SectionDivide/>

      </main>

      <Footer/>
    </div>
  )
}

export default Home
